# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83366adc5b575b8644a00c97494d65ddc4e4fb8f7087b519998057f8f2da06b12b2f6fb850db619f620194f99ee5e980b21fb2aee7d49427846caea0b36f616e

test:
  secret_key_base: ec2754780a6c15abf3f2ea390b1ba90afcde8ee1a148ea47862166e249bb9e8a7eb42f0bddad5602f2d06bca548900a72e246ed892f06c51005f977cbdbaaa8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
