# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 71c9dc28f4fee274e157e74c25d92b1664c289c07fd7d67a7216670d1542e1917f9658df65ffab8c6a0bc25748c0c12391b4f7cb2d0b9b44303d433b901a375b

test:
  secret_key_base: fc76abcee95924c7d567ccbec326e36dbd185a6e74273fbcffd157af4f756b7f70b9f179c98015c358034973ee2dcb240c8400ac4f51373ee995f8092e86cafd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
