# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe4a5cf778f439063e0fbd522bca6d8f1e5a6c503d08b75c62336e5e16052842a06f115d7847baefe9b5ad6db7f9f01f66249a095528405b21deefe0bd1096c6

test:
  secret_key_base: bd30f454a9ea333615a4b286f944147bac86d35f1609a156d325ee43c996e554814ccb8d1e2bfe5f61133102d0236d22cf71d827106a042906014b83e75bde36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
