# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce7d495e45970c40fc2a975e0645cb5dd685de3a7fe032fa2b238f0c62d6559d155d5e3726f8b06d57208e015247c1fccdeb8f745161b6216e5e20eca2880b0a

test:
  secret_key_base: 9dfbe5a002a75ceeb3c726d3c68b7510e5e63233a69351418abf2fe8dba2bb6a7544e4fa5b3e93cdd99e3136fd993fa1c9571acd306faec99983cc5af9b2b2a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
