# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5af3b029f6c25de6c5453f0a81c732bb7ad91e0b264dc615460f2a03cb3bce9296449e03f2ae92bc9950238721ee1dde017db03fe20ca9824250032a3d177591

test:
  secret_key_base: 617740af1dd00fd6424324bc6e55f7cff8b4f4f7831cd5a40c787b21f2ce44fcbd5105dd743ff2c97e4226f22a2c286f594fbc17f958744be4ff62790d4d0ff5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
