# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 949623ae519928e037c075272a5d0fc8dc8c0899a711261cd7fd4e8b61f4e0f343bb206ada029cea17d1a2e6b1f50565f3ba0a2b5fcf830e10047c1b5e3e06b4

test:
  secret_key_base: 338b47b6bfc2ab1a6b4e56ab297197ac6d5bea6e7ce47ce545dda582a7e28a1fbc5988d3f8580fae2e181b6d3f71cd7e10ccdc6467a519d3992e4282aa2ee8e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
