# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5e62af665dfba6f31acde9197c6fb2a9622f99a9ccff4fe8070425d5c8601bb244e697a79f5e893bb739f470429d7c83070d8d6c63c2d3e1bd609206b9a0503

test:
  secret_key_base: a6d0e87b539921a44e01df49f257cfabdc176cf87a9ce90f6ae32e6962cfa248d78f044b8d6e6f01ec32de039ef9fed91f2ccce2a736e557d045cc1d92d50ab0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
