# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51d4d357563cdd08f75bbe5eb69ee40c22ab3a0425cb4183b7385e5ee237d656931dbbb4ce8fb73fb6af2a353adde26ddbb7a08febfc7bc247ddfa5f3895b777

test:
  secret_key_base: aa4416ab7bdfd4146f0a3cc82f1f670a01a4a2fc848708f59669f57892d6f2536f2facc65a2c5ca9ce8fb8b2ea9c7677ba852eb56ee7daf2c74d615b2cdbf48e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
