# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6564aa78a3bbdd2c5aa40ca7ec48faef4646c7e6b2229e3cfd46a10b6bd76026307034300008e1cca3da1c15eb9b7da67a2fbb04505d7b713ba4fc7b9ed3fce5

test:
  secret_key_base: 91bbcc0a98181925679a5a9f05b33ea9bec3c087a9279eed83da8f152896619e69f28c32ff74a74ad11b004db4c43878098a7f45e589a0ea80ee1a17fcf5bca0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
